//
//  TSInspectorView.h
//  Avocado
//
//	This is an object that controls a stack view, which is used to display
//	a series of stacked inspectors.
//
//	NOTE: For state restoration to work properly, there should only be a single
//	instance of a view controller class; if there is more than one instance of
//	the same class, behaviour is undefined.
//
//  Created by Tristan Seifert on 20160514.
//  Copyright © 2016 Tristan Seifert. All rights reserved.
//

#import <Cocoa/Cocoa.h>

#import "TSInspectorViewItem.h"

@interface TSInspectorViewController : NSObject

/**
 * Appends an inspector to the end of the view.
 */
- (void) addInspectorView:(TSInspectorViewItem *) controller;

/**
 * Inserts an inspector view at the given index.
 */
- (void) insertInspectorView:(TSInspectorViewItem *) controller atIndex:(NSUInteger) index;

/**
 * Removes a previously added inspector view.
 */
- (void) removeInspectorView:(TSInspectorViewItem *) controller;

/**
 * All inspector panels currently added to this inspector.
 */
@property (nonatomic, readonly) NSArray<TSInspectorViewItem *> *inspectorItems;

/**
 * Restores the inspector state (including that of its palettes) by parsing
 * the contents of an NSDictionary previously generated by accessing the
 * stateDict property.
 */
- (void) restoreWithState:(NSDictionary *) state;

/**
 * Returns a dictionary containing information for restoring the state of the
 * inspector panels (expansion, size, etc) at a later time.
 */
@property (nonatomic, readonly) NSDictionary *stateDict;

@end
